# Generated by Django 4.1 on 2024-09-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/photos/"
            ),
        ),
    ]
