# Generated by Django 4.1 on 2024-09-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_full_collection_and_more"),
        ("core", "0003_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_photos",
                to="products.product",
            ),
        ),
    ]
