# Generated by Django 5.1.1 on 2024-10-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_photo_product"),
        ("products", "0003_alter_product_full_collection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_photos",
                to="products.product",
            ),
        ),
    ]
